title = "Tower Running USA"
languageCode = "en-us"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[menu]
    [[menu.main]]
    identifier = "Scoring"
    name       = "Scoring"
    url        = "/scoring/"
    weight     = 0

    [[menu.main]]
    identifier = "Calendar"
    name       = "Calendar"
    url        = "/calendar/"
    weight     = 1

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/groups/1531051220545691"
  twitter = ""
  instagram = "https://instagram.com/TowerRunningUSA"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-lightest-blue"
  featured_image = "/images/Chicago_skyline_from_Shedd_Aquarium_2005.jpg"
  recent_posts_number = 2
